### PR TITLE
fix TRICE_OFF

### PR DESCRIPTION
**Pull request by JannisKonradBecker**
with TRICE_OFF defined, trice.h redefines TRICE_ENTER and TRICE_LEAVE

### CODE REVIEW

**Comment by rokath** [comment]
Thanks, for the pull request. Why did you change line 182 as well? (`restrict` --> `__restrict`)

**Comment by JannisKonradBecker** [comment]
sorry, that is an unrelated problem. When including trice.h from c++ code gcc throws this error:
```
trice/trice.h:193:32: error: expected ',' or '...' before 'output'
  193 | int TCOBSEncode(void* restrict output, const void* restrict input, size_t length);
```

**Comment by rokath** [comment]
That´s interesting. In **trice.h** line 8-10 is
```C
#ifdef __cplusplus
extern "C" {
#endif
```
Usually I avoid C++ because all of its nuts and bolts. I could extend the code around line 182 into
```C
#ifdef __cplusplus
int TCOBSEncode( void * __restrict output, const void * __restrict input, size_t length);
#else
int TCOBSEncode( void * restrict output, const void * restrict input, size_t length);
#endif
```
but I assume that´s not the way to do it. Any proposal?

**Comment by JannisKonradBecker** [comment]
I don't see a problem with that solution.

extern "C" only defines C linkage, not C syntax sadly.

__restrict works for GCC in C and C++ mode.
Other C++ compilers might not like restrict at all.

Would this cause Problems?
``` c
#ifdef __cplusplus
int TCOBSEncode( void * output, const void * input, size_t length);
#else
int TCOBSEncode( void * restrict output, const void * restrict input, size_t length);
#endif
```
restrict is still defined in the c file so that code should still be optimized and GCC doesn't complain.

**Comment by rokath** [comment]
For now I added this line to triceConfig.h:
```C
#define RESTRICT restrict //!< Adapt it to your compiler: restrict, __restrict, __restrict__ or empty
```
and changed all occurances of `restrict` to `RESTRICT` to avoid the additional `#ifdef __cplusplus`. I do not like this very much but this allows the users to use the library without modifying the code.

**Comment by JannisKonradBecker** [comment]
Sounds like a good Solution, thanks.

**Pull request merged**
