### PR TITLE
Update  style

### PR DESCRIPTION
**Pull request by Sazerac4**
- Tabulation used instead of space.
- Treat svg files as binary
- Add indentation to preprocessor directives

I suggest a double check of the `f6b7693` commit with preprocessor directives.

### CODE REVIEW

**Comment by Sazerac4** [comment]
Ok. I will do a new pull request.

**Comment by rokath** [comment]
> I suggest a double check of the f6b7693 commit with preprocessor directives.

The `go test ./...` command checks also the target code in many configurations. It runs quite a while but passes. 

Do you have any concerns, what should be tested explicitly? As we know, there is no 100% test.

**Comment by Sazerac4** [comment]
>  I suggest a double check of the f6b7693 commit with preprocessor directives.

I was thinking more about code rendering and readability than functionality.  I don't have specific concern.

**Comment by rokath** [comment]
That's a good hint. I will check later. In general I would exclude the SEGGER code from auto formatting to make it easier to compare against updates.

**Pull request closed without merging**
